export const findTheme = (themeId:number) => {
  return themesSample.find((t) => t.theme===themeId)
}

const themesSample = [
  {
    theme: 1,
    themeName: "기본테마",
    background: "#EEEEEE",
    fontColor: "#000000",
    borderColor: "#000000",
    flag: true,
  },
  {
    theme: 2,
    themeName: "레드",
    background: "#FF0000",
    fontColor: "#FFFFFF",
    borderColor: "#FF0000",
    flag: true,
  },
  {
    theme: 3,
    themeName: "그린",
    background: "#008000",
    fontColor: "#FFFFFF",
    borderColor: "#008000",
    flag: false,
  },
  {
    theme: 4,
    themeName: "노랑",
    background: "#FFFF00",
    fontColor: "#000000",
    borderColor: "#FFFF00",
    flag: false,
  },
  {
    theme: 5,
    themeName: "핑크",
    background: "#FFC0CB",
    fontColor: "#000000",
    borderColor: "#FFC0CB",
    flag: false,
  },
  {
    theme: 6,
    themeName: "보라",
    background: "#800080",
    fontColor: "#FFFFFF",
    borderColor: "#800080",
    flag: false,
  },
  {
    theme: 7,
    themeName: "주황",
    background: "#FFA500",
    fontColor: "#000000",
    borderColor: "#FFA500",
    flag: false,
  },
  {
    theme: 8,
    themeName: "하늘",
    background: "#87CEEB",
    fontColor: "#000000",
    borderColor: "#87CEEB",
    flag: false,
  },
  {
    theme: 9,
    themeName: "회색",
    background: "#808080",
    fontColor: "#FFFFFF",
    borderColor: "#808080",
    flag: false,
  },
  {
    theme: 10,
    themeName: "검정",
    background: "#000000",
    fontColor: "#FFFFFF",
    borderColor: "#000000",
    flag: false,
  },
];
